application: goapprtc
version: 1
runtime: go 
api_version: go1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /html
  static_dir: html

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: _go_app
  secure: always

inbound_services:
- channel_presence
